/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.paneles;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Camion;
import modelo.Coche;
import modelo.Mecanico;
import static vista.Ventanas.VentanaPrincipal.archivoCoche;
import static vista.Ventanas.VentanaPrincipal.archivoMecanico;
import static vista.Ventanas.VentanaPrincipal.centrarColumnas;
import static vista.paneles.PanelMecanico.dataMecanicos;

public class PanelCamion extends javax.swing.JPanel {

    public static DefaultTableModel dtmCamion;
    private Object[] filaCamion = new Object[8];
    private boolean modificar = false;
    private int filaSeleccionada;

    public PanelCamion() {
        initComponents();
        dtmCamion = (DefaultTableModel) tablaCamion.getModel();

        centrarColumnas(tablaCamion);
        llenarTablaCamion();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosCoche = new javax.swing.JPanel();
        matricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        marca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        aceite = new javax.swing.JLabel();
        cmbAceite = new javax.swing.JComboBox<>();
        empresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        numMercncia = new javax.swing.JLabel();
        txtNumMercancia = new javax.swing.JTextField();
        cmbProblemas = new javax.swing.JComboBox<>();
        cmbMecanico2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCamion = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        datosCoche.setBackground(new java.awt.Color(102, 102, 102));
        datosCoche.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos coche camión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 0, 30), new java.awt.Color(0, 0, 0))); // NOI18N
        datosCoche.setMinimumSize(new java.awt.Dimension(0, 0));
        datosCoche.setPreferredSize(new java.awt.Dimension(910, 250));
        datosCoche.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        matricula.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        matricula.setForeground(new java.awt.Color(0, 0, 0));
        matricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Placa.png"))); // NOI18N
        matricula.setText("Matricula");
        datosCoche.add(matricula);

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.setPreferredSize(new java.awt.Dimension(130, 27));
        datosCoche.add(txtMatricula);

        marca.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        marca.setForeground(new java.awt.Color(0, 0, 0));
        marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Marca.png"))); // NOI18N
        marca.setText("Marca");
        datosCoche.add(marca);

        txtMarca.setBackground(new java.awt.Color(255, 255, 255));
        txtMarca.setForeground(new java.awt.Color(0, 0, 0));
        txtMarca.setPreferredSize(new java.awt.Dimension(130, 27));
        datosCoche.add(txtMarca);

        aceite.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        aceite.setForeground(new java.awt.Color(0, 0, 0));
        aceite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/aceite.png"))); // NOI18N
        aceite.setText("Aceite");
        datosCoche.add(aceite);

        cmbAceite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Bueno", "Reemplazar" }));
        cmbAceite.setPreferredSize(new java.awt.Dimension(130, 27));
        datosCoche.add(cmbAceite);

        empresa.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        empresa.setForeground(new java.awt.Color(0, 0, 0));
        empresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Nombre.png"))); // NOI18N
        empresa.setText("Empresa");
        datosCoche.add(empresa);

        txtEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        txtEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        txtEmpresa.setPreferredSize(new java.awt.Dimension(130, 27));
        datosCoche.add(txtEmpresa);

        numMercncia.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        numMercncia.setForeground(new java.awt.Color(0, 0, 0));
        numMercncia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Llantas.png"))); // NOI18N
        numMercncia.setText("Cant mercancia");
        datosCoche.add(numMercncia);

        txtNumMercancia.setBackground(new java.awt.Color(255, 255, 255));
        txtNumMercancia.setForeground(new java.awt.Color(0, 0, 0));
        txtNumMercancia.setPreferredSize(new java.awt.Dimension(130, 27));
        datosCoche.add(txtNumMercancia);

        cmbProblemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Problema a resolver", "Llenar llantas", "Reparar cilindraje", "Pintar coche" }));
        cmbProblemas.setPreferredSize(new java.awt.Dimension(200, 27));
        datosCoche.add(cmbProblemas);

        cmbMecanico2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecánico asignado" }));
        cmbMecanico2.setPreferredSize(new java.awt.Dimension(200, 27));
        datosCoche.add(cmbMecanico2);

        add(datosCoche, java.awt.BorderLayout.NORTH);

        tablaCamion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Marca", "Estado del aceite", "Dueño", "No. mercancía", "Problema", "Mecánico", "Costo reparación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCamion.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCamion);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(102, 102, 102));
        panelBotones.setForeground(new java.awt.Color(102, 102, 102));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 25));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 102));
        btnGuardar.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEliminar.setBackground(new java.awt.Color(0, 153, 102));
        btnEliminar.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        panelBotones.add(btnEliminar);

        btnModificar.setBackground(new java.awt.Color(0, 153, 102));
        btnModificar.setFont(new java.awt.Font("Noto Sans", 0, 20)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        panelBotones.add(btnModificar);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

        if (cmbMecanico2.getItemCount() == 1) {
            JOptionPane.showMessageDialog(this, "No tienes trabajadores, si puedes registralos", "Información", JOptionPane.WARNING_MESSAGE);
        } else if (txtMatricula.getText().isEmpty() || txtMarca.getText().isEmpty()
                || cmbAceite.getSelectedIndex() == 0 || txtEmpresa.getText().isEmpty()
                || cmbProblemas.getSelectedIndex() == 0 || txtNumMercancia.getText().isEmpty()
                || cmbMecanico2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Brinde toda la información pertinente", "Información", JOptionPane.WARNING_MESSAGE);
        } else {

            if (modificar) {

                try {

                    tablaCamion.setValueAt(txtMatricula.getText(), filaSeleccionada, 0);
                    tablaCamion.setValueAt(txtMarca.getText(), filaSeleccionada, 1);
                    tablaCamion.setValueAt(cmbAceite.getSelectedItem(), filaSeleccionada, 2);
                    tablaCamion.setValueAt(txtEmpresa.getText(), filaSeleccionada, 3);
                    tablaCamion.setValueAt(Short.parseShort(txtNumMercancia.getText()), filaSeleccionada, 4);
                    tablaCamion.setValueAt(cmbProblemas.getSelectedItem(), filaSeleccionada, 5);
                    tablaCamion.setValueAt(cmbMecanico2.getSelectedItem(), filaSeleccionada, 6);

                    Mecanico mecanico = archivoMecanico.buscar(dataMecanicos.get((String) cmbMecanico2.getSelectedItem()));

                    Coche cocheAtender = new Camion(txtMarca.getText(), txtMatricula.getText(),
                            (String) cmbAceite.getSelectedItem(), (String) txtEmpresa.getText(),
                            (String) cmbProblemas.getSelectedItem(), mecanico, Integer.parseInt(txtNumMercancia.getText()));
                    cocheAtender.setCostoReparacion();

                    tablaCamion.setValueAt(cocheAtender.getCostoReparacion(), filaSeleccionada, 7);
                    archivoCoche.actualizarCoche(cocheAtender);
                    modificar = false;

                    txtMatricula.setText("");
                    txtMarca.setText("");
                    cmbAceite.setSelectedIndex(0);
                    txtEmpresa.setText("");
                    txtNumMercancia.setText("");
                    cmbProblemas.setSelectedIndex(0);
                    cmbMecanico2.setSelectedIndex(0);

                    txtMatricula.setEnabled(true);
                    JOptionPane.showMessageDialog(this, "Coche modificado", "Guardar", JOptionPane.PLAIN_MESSAGE);

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Cantidad de mercancía es invalida", "Guardar", JOptionPane.WARNING_MESSAGE);
                }
            } else if (archivoCoche.buscar(txtMatricula.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Matricula ya registrada", "Guardar", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    Mecanico mecanico = archivoMecanico.buscar(dataMecanicos.get((String) cmbMecanico2.getSelectedItem()));

                    Coche cocheAtender = new Camion(txtMarca.getText(), txtMatricula.getText(),
                            (String) cmbAceite.getSelectedItem(), (String) txtEmpresa.getText(),
                            (String) cmbProblemas.getSelectedItem(), mecanico, Integer.parseInt(txtNumMercancia.getText()));
                    cocheAtender.setCostoReparacion();

                    filaCamion[0] = txtMatricula.getText();
                    filaCamion[1] = txtMarca.getText();
                    filaCamion[2] = (String) cmbAceite.getSelectedItem();
                    filaCamion[3] = txtEmpresa.getText();
                    filaCamion[4] = Integer.parseInt(txtNumMercancia.getText());
                    filaCamion[5] = cmbProblemas.getSelectedItem();
                    filaCamion[6] = cmbMecanico2.getSelectedItem();
                    filaCamion[7] = cocheAtender.getCostoReparacion();

                    dtmCamion.addRow(filaCamion);
                    archivoCoche.guardarCoche(cocheAtender);

                    txtMatricula.setText("");
                    txtMarca.setText("");
                    cmbAceite.setSelectedIndex(0);
                    txtEmpresa.setText("");
                    txtNumMercancia.setText("");
                    cmbProblemas.setSelectedIndex(0);
                    cmbMecanico2.setSelectedIndex(0);

                    JOptionPane.showMessageDialog(this, "Coche guardado", "Guardar", JOptionPane.PLAIN_MESSAGE);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Cantidad de mercancía es invalida", "Guardar", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked

        if (modificar) {
            JOptionPane.showMessageDialog(this, "Guarde los cambios para poder eliminar",
                    "Eliminar", JOptionPane.WARNING_MESSAGE);
        } else if (tablaCamion.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabla de los coches vacia",
                    "Eliminar", JOptionPane.WARNING_MESSAGE);
        } else if (tablaCamion.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un coche a eliminar",
                    "Eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
            String matriculaCamion = (String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 0);
            String marcaCamion = (String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 1);
            String aceiteCamion = (String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 2);
            String EmpresaCamion = (String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 3);
            int mercanciaE = Integer.parseInt(String.valueOf(tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 4)));
            String problema = (String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 5);

            Mecanico mecanicoEncargado = archivoMecanico.buscar(dataMecanicos.
                    get((String) tablaCamion.getValueAt(tablaCamion.getSelectedRow(), 6)));

            Coche camion = new Camion(marcaCamion, matriculaCamion, aceiteCamion, EmpresaCamion, problema, mecanicoEncargado, mercanciaE);
            dtmCamion.removeRow(tablaCamion.getSelectedRow());
            archivoCoche.eliminarCoche(camion);

            JOptionPane.showMessageDialog(this, "Eliminación con exito",
                    "Eliminar", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        if (tablaCamion.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Sin carros para modificar",
                    "Modificar", JOptionPane.PLAIN_MESSAGE);
        } else if (tablaCamion.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un carro a modificar",
                    "Modificar", JOptionPane.PLAIN_MESSAGE);
        } else {

            int fila = tablaCamion.getSelectedRow();
            txtMatricula.setText((String) tablaCamion.getValueAt(fila, 0));
            txtMarca.setText((String) tablaCamion.getValueAt(fila, 1));
            cmbAceite.setSelectedItem((String) tablaCamion.getValueAt(fila, 2));
            txtEmpresa.setText((String) tablaCamion.getValueAt(fila, 3));
            txtNumMercancia.setText(String.valueOf(tablaCamion.getValueAt(fila, 4)));
            cmbProblemas.setSelectedItem((String) tablaCamion.getValueAt(fila, 5));
            cmbMecanico2.setSelectedItem((String) tablaCamion.getValueAt(fila, 6));

            txtMatricula.setEnabled(false);
            filaSeleccionada = tablaCamion.getSelectedRow();
            this.modificar = true;
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void llenarTablaCamion() {
        for (Coche coche : archivoCoche.listarCoches()) {

            if (coche instanceof Camion) {
                Camion cocheCamion = (Camion) coche;

                filaCamion[0] = cocheCamion.getMatricula();
                filaCamion[1] = cocheCamion.getMarca();
                filaCamion[2] = cocheCamion.getAceite();
                filaCamion[3] = cocheCamion.getPoseedor();
                filaCamion[4] = cocheCamion.getMercancia();
                filaCamion[5] = cocheCamion.getProblema();
                filaCamion[6] = cocheCamion.getMecanicoEncargado().getNombre();
                filaCamion[7] = cocheCamion.getCostoReparacion();

                dtmCamion.addRow(filaCamion);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aceite;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbAceite;
    public static javax.swing.JComboBox<String> cmbMecanico2;
    private javax.swing.JComboBox<String> cmbProblemas;
    private javax.swing.JPanel datosCoche;
    private javax.swing.JLabel empresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel matricula;
    private javax.swing.JLabel numMercncia;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaCamion;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNumMercancia;
    // End of variables declaration//GEN-END:variables
}
